name: Run Coverage on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Run Tests and Coverage
        run: npm run coverage

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
